version: "3.7"

services:
  postgres:
    container_name: postgres-container
    image: library/postgres:9.6-alpine
    ports: 
      - "5431:5432"
    volumes: 
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES=database,test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root@123
    restart: always
    networks:
      - default

  adminer:
    container_name: adminer-container
    image: adminer
    ports:
      - 8080:8080
    restart: always
    networks:
      - default