version: "3.7"

services:
  api:
    container_name: "api-container"
    image: node:14.5.0-slim
    entrypoint: ./.docker/entrypoint.sh
    working_dir: /home/backend/
    volumes:
      - ./:/home/backend/
    ports: 
      - "3333:3333"
    environment:
      - DB_URI=postgres
    depends_on: 
      - postgres
    networks:
      - app-network

  postgres:
    container_name: postgres-container
    image: library/postgres:9.6-alpine
    ports: 
      - "5431:5432"
    volumes: 
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES=production,test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root@123
    restart: always
    networks:
      - app-network
    
  adminer:
    container_name: adminer-container
    image: adminer
    ports:
      - 8080:8080
    restart: always
    depends_on: 
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"